package com.nikhil.yt.spotify.models
import kotlinx.serialization.SerialName; import kotlinx.serialization.Serializable
@Serializable data class SpotifyImage(val url: String = "", @SerialName("width") val width: Int? = null, @SerialName("height") val height: Int? = null)
@Serializable data class SpotifyArtistSimple(val id: String = "", val name: String = "", val uri: String = "")
@Serializable data class SpotifyAlbumSimple(val id: String = "", val name: String = "", val images: List<SpotifyImage> = emptyList(), val uri: String = "")
@Serializable data class SpotifyFollowers(@SerialName("total") val total: Int = 0)
@Serializable data class SpotifyArtist(val id: String = "", val name: String = "", val images: List<SpotifyImage> = emptyList(), val followers: SpotifyFollowers? = null, val uri: String = "", val popularity: Int? = null, val type: String = "artist")
@Serializable data class SpotifyAlbum(val id: String = "", val name: String = "", val artists: List<SpotifyArtistSimple> = emptyList(), val images: List<SpotifyImage> = emptyList(), @SerialName("release_date") val releaseDate: String? = null, @SerialName("total_tracks") val totalTracks: Int = 0, val uri: String = "")
@Serializable data class SpotifyTrack(val id: String = "", val name: String = "", val artists: List<SpotifyArtistSimple> = emptyList(), val album: SpotifyAlbumSimple? = null, @SerialName("duration_ms") val durationMs: Long = 0, val uri: String = "")
@Serializable data class SpotifyPlaylistSimple(val id: String = "", val name: String = "", val description: String? = null, val images: List<SpotifyImage> = emptyList(), val uri: String = "", @SerialName("tracks") val tracks: SpotifyPlaylistTracksRef? = null)
@Serializable data class SpotifyPlaylistTracksRef(val href: String = "", val total: Int = 0)
@Serializable data class SpotifyPlaylistTrack(@SerialName("added_at") val addedAt: String? = null, val track: SpotifyTrack? = null)
@Serializable data class SpotifySearchResult(val albums: SpotifyPaging<SpotifyAlbum>? = null, val artists: SpotifyPaging<SpotifyArtist>? = null, val tracks: SpotifyPaging<SpotifyTrack>? = null, val playlists: SpotifyPaging<SpotifyPlaylistSimple>? = null)
@Serializable data class SpotifyRecommendations(val tracks: List<SpotifyTrack> = emptyList())
@Serializable data class SpotifyRecommendationSeed(@SerialName("initialPoolSize") val initialPoolSize: Int = 0, val id: String = "", val type: String = "")
@Serializable data class SpotifyLibraryItem(@SerialName("added_at") val addedAt: String? = null, val track: SpotifyTrack? = null)
@Serializable data class SpotifyLibraryFolder(val id: String = "", val name: String = "", val uri: String = "", @SerialName("image_url") val imageUrl: String? = null)
@Serializable data class SpotifyHomeFeed(val sections: List<SpotifyHomeFeedSection> = emptyList())
@Serializable data class SpotifyHomeFeedSection(val id: String? = null, val title: String? = null, val items: List<SpotifyHomeFeedItem> = emptyList(), val type: String? = null)
@Serializable data class SpotifyHomeFeedItem(val uri: String = "", val type: String = "", val album: SpotifyAlbum? = null, val artist: SpotifyArtist? = null, val track: SpotifyTrack? = null, val playlist: SpotifyPlaylistSimple? = null, val image: SpotifyImage? = null, val title: String? = null, val subtitle: String? = null)
@Serializable data class SpotifyPaging<T>(val href: String = "", val items: List<T> = emptyList(), val limit: Int = 20, val next: String? = null, val offset: Int = 0, val previous: String? = null, val total: Int = 0)
@Serializable data class SpotifyUserPrivate(val id: String = "", @SerialName("display_name") val displayName: String? = null, val email: String? = null, val images: List<SpotifyImage> = emptyList(), val uri: String = "")
